NAV_BY_ROLE = {
    "admin": [
        ("/dashboard", "لوحة المدير"),
        ("/owner-financial", "تقرير المالك المالي"),
        ("/accounting", "النظام المحاسبي"),
        ("/clients", "العملاء"),
        ("/matters", "القضايا"),
        ("/sessions", "الجلسات"),
        ("/tasks", "المهام"),
        ("/documents", "المستندات"),
        ("/invoices", "الفواتير"),
        ("/payments", "المدفوعات"),
        ("/appointments", "حجوزات العملاء"),
        ("/consultations", "الاستشارات"),
        ("/reports", "التقارير"),
        ("/audit", "سجل التدقيق"),
        ("/settings", "الإعدادات"),
        ("/whatsapp/templates", "قوالب واتساب"),
        ("/users", "المستخدمون"),
    ],
    "lawyer": [
        ("/dashboard", "لوحة المحامي"),
        ("/matters", "قضاياي"),
        ("/sessions", "جلساتي"),
        ("/tasks", "مهامي"),
        ("/documents", "المستندات"),
        ("/appointments", "حجوزات العملاء"),
        ("/clients", "العملاء"),
        ("/consultations", "الاستشارات"),
    ],
    "secretary": [
        ("/dashboard", "لوحة السكرتير"),
        ("/clients", "العملاء"),
        ("/sessions", "الجلسات"),
        ("/tasks", "المهام"),
        ("/documents", "المستندات"),
        ("/appointments", "حجوزات العملاء"),
        ("/consultations", "الاستشارات"),
        ("/matters", "القضايا"),
    ],
    "accountant": [
        ("/accounting", "لوحة المحاسب المالية"),
        ("/accounting/overdue-clients", "التحصيل والمتأخرات"),
        ("/accounting/clients", "أرصدة العملاء"),
        ("/accounting/case-fees", "أتعاب القضايا"),
        ("/accounting/receipts", "سندات القبض"),
        ("/accounting/payment-vouchers", "سندات الصرف"),
        ("/accounting/expenses", "المصروفات"),
        ("/accounting/installments", "الأقساط"),
        ("/accounting/fixed-expenses", "التكاليف الثابتة"),
        ("/accounting/accounts", "الحسابات المالية"),
        ("/accounting/journal", "القيود اليومية"),
        ("/accounting/chart", "دليل الحسابات"),
        ("/accounting/reports", "تقارير IFRS"),
        ("/invoices", "الفواتير"),
        ("/payments", "المدفوعات"),
        ("/tasks", "المهام المالية"),
    ],
    "data_entry": [
        ("/dashboard", "لوحة مدخل البيانات"),
        ("/clients", "إدخال العملاء"),
        ("/matters", "إدخال القضايا"),
        ("/sessions", "إدخال الجلسات"),
        ("/tasks", "المهام"),
        ("/documents", "المستندات"),
        ("/appointments", "حجوزات العملاء"),
        ("/consultations", "الاستشارات"),
    ],
    "viewer": [
        ("/dashboard", "لوحة المشاهدة"),
        ("/accounting/fixed-expenses", "المصاريف الشهرية الثابتة"),
        ("/clients", "العملاء"),
        ("/matters", "القضايا"),
        ("/sessions", "الجلسات"),
        ("/tasks", "المهام"),
        ("/documents", "المستندات"),
        ("/invoices", "الفواتير"),
        ("/payments", "المدفوعات"),
        ("/appointments", "حجوزات العملاء"),
        ("/consultations", "الاستشارات"),
        ("/reports", "التقارير"),
    ],
}


def nav_for_role(role: str) -> list[tuple[str, str]]:
    return NAV_BY_ROLE.get(role, NAV_BY_ROLE["viewer"])
